# ----
# Site

title: CMAC Makerbot
url: "http://yourdomain.com"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: "Documentation For CMAC Makerbot 3D Printer"
author: 
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: CMAC
  links:
    - http://yourdomain.com

# -----
# Build

permalink: pretty

gems:

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release



types:
  - minor
  - major
